### PR TITLE
Sync with upstream repo - v1.0.1.5 v3

### PR DESCRIPTION
**Pull request by AthenaSulisMinerva**
Bringing in changes from the upstream repo for the official 1.0.1.5a hotfix.

Will require some manual fixes for CE:FT.

### CODE REVIEW

**Comment by AthenaSulisMinerva** [comment]
@sumghai I need you to help me approve some of NiA's About.xml file changes from upstream, so that I can put our own About.xml back later.

**Comment by sumghai** [comment]
Oh joy, this will be a real doozy. Let me take a look.

**Comment by sumghai** [comment]
Uhh nope, that did nothing.

You might have to fix it on your end with the command line.

**Comment by AthenaSulisMinerva** [comment]
Okay. Give me a moment.

**Comment by AthenaSulisMinerva** [comment]
@sumghai - I'm trying to roll back to the older versions of NiA's files, and I've got most of them working except for Manifest.xml, which doesn't seem to recognize that I've manually reverted it back to its pre-patched state (if you know what I mean).

**Comment by AthenaSulisMinerva** [comment]
(NiA is probably watching all this and thinking it's all a big joke, huh?)

**Comment by sumghai** [comment]
Yay, it's fixed!

Nah, I don't think NiA would care. He does what he does, we do what we do. No dramas.

**Pull request merged**
